P9K_MODE="nerdfont-complete"

P9K_PROMPT_ON_NEWLINE=true
P9K_RPROMPT_ICON_LEFT=true
# P9K_RPROMPT_ON_NEWLINE=true

P9K_LEFT_PROMPT_ELEMENTS=(dir_writable user dir vcs )
P9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time root_indicator background_jobs  disk_usage ram time )
# time os_icon
P9K_NODE_VERSION_FOREGROUND="black"
P9K_TIME_ICON=""
P9K_NEWLINE_ICON="\uF09C"
# P9K_TIME_RIGHT_WHITESPACE=" "
P9K_TIME_ICON_COLOR='green'

P9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL="\ue0b2"
# P9K_LEFT_PROMPT_FIRST_SEGMENT_START_WHITESPACE=" "

P9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL="\ue0b0" # 
# P9K_RIGHT_PROMPT_LAST_SEGMENT_END_WHITESPACE=" "

P9K_WHITESPACE_BETWEEN_LEFT_SEGMENTS=" "
P9K_WHITESPACE_BETWEEN_RIGHT_SEGMENTS=""

# P9K_LEFT_WHITESPACE_OF_LEFT_SEGMENTS=" "
# P9K_RIGHT_WHITESPACE_OF_LEFT_SEGMENTS=" "

# P9K_LEFT_WHITESPACE_OF_RIGHT_SEGMENTS=" "
# P9K_RIGHT_WHITESPACE_OF_RIGHT_SEGMENTS=" "

P9K_LEFT_SEGMENT_SEPARATOR_ICON="\ue0b0"
P9K_LEFT_SUBSEGMENT_SEPARATOR_ICON="\ue0b1"
P9K_RIGHT_SEGMENT_SEPARATOR_ICON="\ue0b2"
P9K_RIGHT_SUBSEGMENT_SEPARATOR_ICON="\ue0b3"

P9K_MULTILINE_FIRST_PROMPT_PREFIX_ICON="%F{blue}"$'\u256D\u2500'"%F{white}" # ╭─
P9K_MULTILINE_LAST_PROMPT_PREFIX_ICON="%F{blue}"$'\u2570\uf460'"%F{white}" # ╰

#P9K_WHITESPACE_BETWEEN_LEFT_SEGMENTS=" "

#P9K_USER_ICON="\uF415" # 
P9K_USER_ROOT_ICON="\uF09C"
P9K_USER_SUDO_ICON="\uF09C" # 
P9K_TIME_FORMAT="%D{%H:%M}"
#P9K_VCS_GIT_ICON='\uF408 '
#P9K_VCS_GIT_GITHUB_ICON='\uF408 '

P9K_CUSTOM_SEGMENT="echo "
#P9K_CUSTOM_SEGMENT_ICON="\uf109"
P9K_CUSTOM_SEGMENT_BACKGROUND="black"
P9K_CUSTOM_SEGMENT_FOREGROUND="white"

ZSH_DISABLE_COMPFIX=true

ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"

P9K_VCS_SHORTEN_LENGTH=4
P9K_VCS_SHORTEN_MIN_LENGTH=11
P9K_VCS_SHORTEN_STRATEGY="truncate_from_right"
P9K_VCS_SHORTEN_DELIMITER="…"
P9K_DIR_SHORTEN_DELIMITER="…"
